# Generated by Django 6.0.2 on 2026-02-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
